# Generated by Django 4.2.10 on 2025-11-27 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passage',
            name='tier',
            field=models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='free', max_length=10),
        ),
        migrations.AddIndex(
            model_name='passage',
            index=models.Index(fields=['tier'], name='passages_tier_e37728_idx'),
        ),
    ]
