# Generated by Django 4.2.10 on 2025-11-28 19:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_is_premium_user_stripe_customer_id_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassageAnnotation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_char', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('end_char', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('selected_text', models.TextField()),
                ('explanation', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('passage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='api.passage')),
            ],
            options={
                'db_table': 'passage_annotations',
                'ordering': ['start_char'],
                'indexes': [models.Index(fields=['passage'], name='passage_ann_passage_d2005f_idx'), models.Index(fields=['start_char', 'end_char'], name='passage_ann_start_c_ce580a_idx')],
            },
        ),
    ]
