# Generated by Django 4.2.10 on 2025-11-28 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_passageannotation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passageannotation',
            options={'ordering': ['question__order', 'start_char']},
        ),
        migrations.AddField(
            model_name='passageannotation',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='api.question'),
        ),
        migrations.AddIndex(
            model_name='passageannotation',
            index=models.Index(fields=['question'], name='passage_ann_questio_f066e2_idx'),
        ),
    ]
