# Generated by Django 4.2.10 on 2025-12-03 05:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20251128_2108'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordOfTheDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('word', models.CharField(max_length=100, unique=True)),
                ('definition', models.TextField()),
                ('synonyms', models.JSONField(default=list)),
                ('example_sentence', models.TextField()),
                ('date', models.DateField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'word_of_the_day',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='word_of_the_date_e32374_idx')],
            },
        ),
    ]
