# Generated by Django 4.2.10 on 2025-12-06 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_passageingestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='passageingestion',
            name='file_paths',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
