# Generated by Django 4.2.10 on 2025-12-06 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_passageingestion_file_paths'),
    ]

    operations = [
        migrations.AddField(
            model_name='passageingestion',
            name='parsed_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
