# Generated by Django 4.2.10 on 2025-12-06 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_add_parsed_data_to_ingestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='passage',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
