# Generated by Django 4.2.10 on 2025-12-20 04:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_add_content_hash_to_passage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PassageAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('correct_count', models.IntegerField()),
                ('total_questions', models.IntegerField()),
                ('time_spent_seconds', models.IntegerField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('answers_data', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'passage_attempts',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='passage',
            name='content_hash',
        ),
        migrations.RemoveField(
            model_name='passageingestion',
            name='parsed_data',
        ),
        migrations.AddIndex(
            model_name='useranswer',
            index=models.Index(fields=['answered_at'], name='user_answer_answere_ca581f_idx'),
        ),
        migrations.AddField(
            model_name='passageattempt',
            name='passage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='api.passage'),
        ),
        migrations.AddField(
            model_name='passageattempt',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passage_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='passageattempt',
            index=models.Index(fields=['user', 'passage'], name='passage_att_user_id_fca787_idx'),
        ),
        migrations.AddIndex(
            model_name='passageattempt',
            index=models.Index(fields=['user'], name='passage_att_user_id_fab5b0_idx'),
        ),
        migrations.AddIndex(
            model_name='passageattempt',
            index=models.Index(fields=['passage'], name='passage_att_passage_aa8e6d_idx'),
        ),
        migrations.AddIndex(
            model_name='passageattempt',
            index=models.Index(fields=['completed_at'], name='passage_att_complet_6d89ba_idx'),
        ),
    ]
