# Generated by Django 4.2.10 on 2025-12-20 20:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_add_passage_attempts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lesson_id', models.CharField(help_text="Unique identifier from JSON (e.g., 'commas')", max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('chunks', models.JSONField(default=list, help_text='Structured content chunks from JSON')),
                ('content', models.TextField(blank=True, help_text='Rendered/flattened content for display')),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', max_length=10)),
                ('tier', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='free', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lessons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField(help_text='Question prompt')),
                ('correct_answer_index', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('explanation', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(help_text='Order in the lesson (based on chunk position)')),
                ('chunk_index', models.IntegerField(help_text='Index of the question chunk in the chunks array')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.lesson')),
            ],
            options={
                'db_table': 'lesson_questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LessonQuestionOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('order', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.lessonquestion')),
            ],
            options={
                'db_table': 'lesson_question_options',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LessonIngestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('parsed_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingestions', to='api.lesson')),
            ],
            options={
                'db_table': 'lesson_ingestions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['lesson_id'], name='lessons_lesson__7583ad_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['difficulty'], name='lessons_difficu_5ad1ec_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['tier'], name='lessons_tier_b42468_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonquestionoption',
            index=models.Index(fields=['question'], name='lesson_ques_questio_bf508d_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonquestionoption',
            index=models.Index(fields=['order'], name='lesson_ques_order_b8260c_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonquestion',
            index=models.Index(fields=['lesson'], name='lesson_ques_lesson__c7ba27_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonquestion',
            index=models.Index(fields=['order'], name='lesson_ques_order_a6b3e6_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonquestion',
            index=models.Index(fields=['chunk_index'], name='lesson_ques_chunk_i_bc662f_idx'),
        ),
    ]
