# Generated by Django 4.2.10 on 2025-12-22 02:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_add_lessons'),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], max_length=10)),
                ('tier', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='free', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'writing_sections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WritingSectionQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('correct_answer_index', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('explanation', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField()),
                ('selection_number', models.IntegerField(blank=True, help_text='The selection number this question refers to (if any)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('writing_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.writingsection')),
            ],
            options={
                'db_table': 'writing_section_questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WritingSectionSelection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.IntegerField(help_text='The number shown next to the underlined text (e.g., [1])', validators=[django.core.validators.MinValueValidator(1)])),
                ('start_char', models.IntegerField(help_text='Start character position in content', validators=[django.core.validators.MinValueValidator(0)])),
                ('end_char', models.IntegerField(help_text='End character position (exclusive)', validators=[django.core.validators.MinValueValidator(0)])),
                ('selected_text', models.TextField(help_text='The actual underlined text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('writing_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='api.writingsection')),
            ],
            options={
                'db_table': 'writing_section_selections',
                'ordering': ['number', 'start_char'],
            },
        ),
        migrations.CreateModel(
            name='WritingSectionQuestionOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('order', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.writingsectionquestion')),
            ],
            options={
                'db_table': 'writing_section_question_options',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WritingSectionIngestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('parsed_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_writing_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingestions', to='api.writingsection')),
            ],
            options={
                'db_table': 'writing_section_ingestions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='writingsection',
            index=models.Index(fields=['difficulty'], name='writing_sec_difficu_bc4eac_idx'),
        ),
        migrations.AddIndex(
            model_name='writingsection',
            index=models.Index(fields=['tier'], name='writing_sec_tier_e2abcc_idx'),
        ),
        migrations.AddIndex(
            model_name='writingsectionselection',
            index=models.Index(fields=['writing_section'], name='writing_sec_writing_d444cb_idx'),
        ),
        migrations.AddIndex(
            model_name='writingsectionselection',
            index=models.Index(fields=['number'], name='writing_sec_number_5cdac3_idx'),
        ),
        migrations.AddIndex(
            model_name='writingsectionselection',
            index=models.Index(fields=['start_char', 'end_char'], name='writing_sec_start_c_ecae4f_idx'),
        ),
        migrations.AddIndex(
            model_name='writingsectionquestionoption',
            index=models.Index(fields=['question'], name='writing_sec_questio_365a78_idx'),
        ),
        migrations.AddIndex(
            model_name='writingsectionquestionoption',
            index=models.Index(fields=['order'], name='writing_sec_order_783029_idx'),
        ),
        migrations.AddIndex(
            model_name='writingsectionquestion',
            index=models.Index(fields=['writing_section'], name='writing_sec_writing_aaaff1_idx'),
        ),
        migrations.AddIndex(
            model_name='writingsectionquestion',
            index=models.Index(fields=['order'], name='writing_sec_order_f1ba1e_idx'),
        ),
        migrations.AddIndex(
            model_name='writingsectionquestion',
            index=models.Index(fields=['selection_number'], name='writing_sec_selecti_570226_idx'),
        ),
    ]
