# Generated by Django 4.2.10 on 2025-12-22 03:56

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_add_writing_sections'),
    ]

    operations = [
        migrations.CreateModel(
            name='WritingSectionAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('correct_count', models.IntegerField()),
                ('total_questions', models.IntegerField()),
                ('time_spent_seconds', models.IntegerField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('answers_data', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='writing_section_attempts', to=settings.AUTH_USER_MODEL)),
                ('writing_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='api.writingsection')),
            ],
            options={
                'db_table': 'writing_section_attempts',
                'ordering': ['-completed_at'],
                'indexes': [models.Index(fields=['user', 'writing_section'], name='writing_sec_user_id_97e760_idx'), models.Index(fields=['user'], name='writing_sec_user_id_627ac3_idx'), models.Index(fields=['writing_section'], name='writing_sec_writing_1ef100_idx'), models.Index(fields=['completed_at'], name='writing_sec_complet_49ba47_idx')],
            },
        ),
    ]
