# Generated by Django 4.2.10 on 2025-12-25 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_add_writing_section_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='passageingestion',
            name='parsed_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
