# Generated by Django 4.2.10 on 2025-12-25 20:07

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_passageingestion_parsed_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='MathAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_id', models.CharField(help_text="Unique identifier from JSON (e.g., 'diagram-1')", max_length=255)),
                ('type', models.CharField(choices=[('image', 'Image')], default='image', max_length=50)),
                ('s3_url', models.URLField(help_text='Public S3 URL for the asset', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'math_assets',
            },
        ),
        migrations.CreateModel(
            name='MathQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_id', models.CharField(help_text="Unique identifier from JSON (e.g., 'q1')", max_length=255)),
                ('prompt', models.TextField(help_text='Question prompt')),
                ('correct_answer_index', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('explanation', models.JSONField(default=list, help_text='Array of explanation blocks')),
                ('order', models.IntegerField(help_text='Order of the question')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'math_questions',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MathQuestionAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'math_question_assets',
            },
        ),
        migrations.CreateModel(
            name='MathQuestionOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('order', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'math_question_options',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MathSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_id', models.CharField(help_text="Unique identifier from JSON (e.g., 'algebra-basics')", max_length=255, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('difficulty', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Medium', max_length=10)),
                ('tier', models.CharField(choices=[('free', 'Free'), ('premium', 'Premium')], default='free', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'math_sections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MathSectionIngestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('parsed_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_math_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingestions', to='api.mathsection')),
            ],
            options={
                'db_table': 'math_section_ingestions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MathSectionAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('correct_count', models.IntegerField()),
                ('total_questions', models.IntegerField()),
                ('time_spent_seconds', models.IntegerField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('answers_data', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('math_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='api.mathsection')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='math_section_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'math_section_attempts',
                'ordering': ['-completed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='mathsection',
            index=models.Index(fields=['section_id'], name='math_sectio_section_1bcfdd_idx'),
        ),
        migrations.AddIndex(
            model_name='mathsection',
            index=models.Index(fields=['difficulty'], name='math_sectio_difficu_203c3b_idx'),
        ),
        migrations.AddIndex(
            model_name='mathsection',
            index=models.Index(fields=['tier'], name='math_sectio_tier_c925ac_idx'),
        ),
        migrations.AddField(
            model_name='mathquestionoption',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='api.mathquestion'),
        ),
        migrations.AddField(
            model_name='mathquestionasset',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_references', to='api.mathasset'),
        ),
        migrations.AddField(
            model_name='mathquestionasset',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_assets', to='api.mathquestion'),
        ),
        migrations.AddField(
            model_name='mathquestion',
            name='math_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.mathsection'),
        ),
        migrations.AddField(
            model_name='mathasset',
            name='math_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='api.mathsection'),
        ),
        migrations.AddIndex(
            model_name='mathsectionattempt',
            index=models.Index(fields=['user', 'math_section'], name='math_sectio_user_id_dbf5b0_idx'),
        ),
        migrations.AddIndex(
            model_name='mathsectionattempt',
            index=models.Index(fields=['user'], name='math_sectio_user_id_b3043b_idx'),
        ),
        migrations.AddIndex(
            model_name='mathsectionattempt',
            index=models.Index(fields=['math_section'], name='math_sectio_math_se_71c8b5_idx'),
        ),
        migrations.AddIndex(
            model_name='mathsectionattempt',
            index=models.Index(fields=['completed_at'], name='math_sectio_complet_5ce3c6_idx'),
        ),
        migrations.AddIndex(
            model_name='mathquestionoption',
            index=models.Index(fields=['question'], name='math_questi_questio_0dec73_idx'),
        ),
        migrations.AddIndex(
            model_name='mathquestionoption',
            index=models.Index(fields=['order'], name='math_questi_order_0cadee_idx'),
        ),
        migrations.AddIndex(
            model_name='mathquestionasset',
            index=models.Index(fields=['question'], name='math_questi_questio_fc9c18_idx'),
        ),
        migrations.AddIndex(
            model_name='mathquestionasset',
            index=models.Index(fields=['asset'], name='math_questi_asset_i_68112e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mathquestionasset',
            unique_together={('question', 'asset')},
        ),
        migrations.AddIndex(
            model_name='mathquestion',
            index=models.Index(fields=['math_section'], name='math_questi_math_se_526797_idx'),
        ),
        migrations.AddIndex(
            model_name='mathquestion',
            index=models.Index(fields=['question_id'], name='math_questi_questio_a6cbce_idx'),
        ),
        migrations.AddIndex(
            model_name='mathquestion',
            index=models.Index(fields=['order'], name='math_questi_order_0fc44b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mathquestion',
            unique_together={('math_section', 'question_id')},
        ),
        migrations.AddIndex(
            model_name='mathasset',
            index=models.Index(fields=['math_section'], name='math_assets_math_se_b9c13a_idx'),
        ),
        migrations.AddIndex(
            model_name='mathasset',
            index=models.Index(fields=['asset_id'], name='math_assets_asset_i_a5c844_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='mathasset',
            unique_together={('math_section', 'asset_id')},
        ),
    ]
