# Generated by Django 4.2.10 on 2025-12-25 22:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_mathasset_mathquestion_mathquestionasset_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('asset_id', models.CharField(help_text="Unique identifier from JSON (e.g., 'diagram-1')", max_length=255)),
                ('type', models.CharField(choices=[('image', 'Image')], default='image', max_length=50)),
                ('s3_url', models.URLField(help_text='Public S3 URL for the asset', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='api.lesson')),
            ],
            options={
                'db_table': 'lesson_assets',
            },
        ),
        migrations.CreateModel(
            name='LessonQuestionAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_references', to='api.lessonasset')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_assets', to='api.lessonquestion')),
            ],
            options={
                'db_table': 'lesson_question_assets',
                'indexes': [models.Index(fields=['question'], name='lesson_ques_questio_f8eb44_idx'), models.Index(fields=['asset'], name='lesson_ques_asset_i_2773ba_idx')],
                'unique_together': {('question', 'asset')},
            },
        ),
        migrations.AddIndex(
            model_name='lessonasset',
            index=models.Index(fields=['lesson'], name='lesson_asse_lesson__58a267_idx'),
        ),
        migrations.AddIndex(
            model_name='lessonasset',
            index=models.Index(fields=['asset_id'], name='lesson_asse_asset_i_6538b0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='lessonasset',
            unique_together={('lesson', 'asset_id')},
        ),
    ]
