# Generated by Django 4.2.10 on 2025-12-26 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_lessonasset_lessonquestionasset_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['-display_order', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='mathsection',
            options={'ordering': ['-display_order', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='passage',
            options={'ordering': ['-display_order', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='writingsection',
            options={'ordering': ['-display_order', '-created_at']},
        ),
        migrations.AddField(
            model_name='lesson',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Order for display in admin (higher numbers appear first)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='lesson_type',
            field=models.CharField(choices=[('reading', 'Reading'), ('writing', 'Writing'), ('math', 'Math')], default='reading', help_text='Category: reading, writing, or math', max_length=20),
        ),
        migrations.AddField(
            model_name='mathsection',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Order for display in admin (higher numbers appear first)'),
        ),
        migrations.AddField(
            model_name='passage',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Order for display in admin (higher numbers appear first)'),
        ),
        migrations.AddField(
            model_name='writingsection',
            name='display_order',
            field=models.IntegerField(default=0, help_text='Order for display in admin (higher numbers appear first)'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['lesson_type'], name='lessons_lesson__5ca97f_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['display_order'], name='lessons_display_b5df3f_idx'),
        ),
        migrations.AddIndex(
            model_name='mathsection',
            index=models.Index(fields=['display_order'], name='math_sectio_display_1a096f_idx'),
        ),
        migrations.AddIndex(
            model_name='passage',
            index=models.Index(fields=['display_order'], name='passages_display_07aa14_idx'),
        ),
        migrations.AddIndex(
            model_name='writingsection',
            index=models.Index(fields=['display_order'], name='writing_sec_display_cc1538_idx'),
        ),
    ]
