# Generated by Django 4.2.10 on 2025-12-27 20:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_add_display_order_and_lesson_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text="Header title (e.g., 'Algebra Basics', 'Grammar Rules')", max_length=255)),
                ('category', models.CharField(choices=[('reading', 'Reading'), ('writing', 'Writing'), ('math', 'Math')], help_text='Category this header belongs to', max_length=20)),
                ('display_order', models.IntegerField(default=0, help_text='Order for display within category (higher numbers appear first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'headers',
                'ordering': ['category', '-display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='MathLesson',
            fields=[
            ],
            options={
                'verbose_name': 'Math Lesson',
                'verbose_name_plural': 'Math Lessons',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.lesson',),
        ),
        migrations.CreateModel(
            name='ReadingLesson',
            fields=[
            ],
            options={
                'verbose_name': 'Reading Lesson',
                'verbose_name_plural': 'Reading Lessons',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.lesson',),
        ),
        migrations.CreateModel(
            name='WritingLesson',
            fields=[
            ],
            options={
                'verbose_name': 'Writing Lesson',
                'verbose_name_plural': 'Writing Lessons',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('api.lesson',),
        ),
        migrations.AlterModelOptions(
            name='lesson',
            options={'ordering': ['header', '-order_within_header', '-display_order', '-created_at']},
        ),
        migrations.AddField(
            model_name='lesson',
            name='order_within_header',
            field=models.IntegerField(default=0, help_text='Order within the header (higher numbers appear first)'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='header',
            field=models.ForeignKey(blank=True, help_text='Header/section this lesson belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lessons', to='api.header'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['header'], name='lessons_header__3161ca_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['order_within_header'], name='lessons_order_w_8bfcbc_idx'),
        ),
        migrations.AddIndex(
            model_name='header',
            index=models.Index(fields=['category'], name='headers_categor_12c398_idx'),
        ),
        migrations.AddIndex(
            model_name='header',
            index=models.Index(fields=['display_order'], name='headers_display_a53323_idx'),
        ),
    ]
