# Generated by Django 4.2.10 on 2025-12-29 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_add_header_system'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mathsection',
            options={'ordering': ['header', '-order_within_header', '-display_order', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='passage',
            options={'ordering': ['header', '-order_within_header', '-display_order', '-created_at']},
        ),
        migrations.AlterModelOptions(
            name='writingsection',
            options={'ordering': ['header', '-order_within_header', '-display_order', '-created_at']},
        ),
        migrations.AddField(
            model_name='mathsection',
            name='header',
            field=models.ForeignKey(blank=True, help_text='Header/section this math section belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='math_sections', to='api.header'),
        ),
        migrations.AddField(
            model_name='mathsection',
            name='order_within_header',
            field=models.IntegerField(default=0, help_text='Order within the header (higher numbers appear first)'),
        ),
        migrations.AddField(
            model_name='passage',
            name='header',
            field=models.ForeignKey(blank=True, help_text='Header/section this passage belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passages', to='api.header'),
        ),
        migrations.AddField(
            model_name='passage',
            name='order_within_header',
            field=models.IntegerField(default=0, help_text='Order within the header (higher numbers appear first)'),
        ),
        migrations.AddField(
            model_name='writingsection',
            name='header',
            field=models.ForeignKey(blank=True, help_text='Header/section this writing section belongs to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='writing_sections', to='api.header'),
        ),
        migrations.AddField(
            model_name='writingsection',
            name='order_within_header',
            field=models.IntegerField(default=0, help_text='Order within the header (higher numbers appear first)'),
        ),
        migrations.AddIndex(
            model_name='mathsection',
            index=models.Index(fields=['header'], name='math_sectio_header__7df9ae_idx'),
        ),
        migrations.AddIndex(
            model_name='mathsection',
            index=models.Index(fields=['order_within_header'], name='math_sectio_order_w_376089_idx'),
        ),
        migrations.AddIndex(
            model_name='passage',
            index=models.Index(fields=['header'], name='passages_header__f9befd_idx'),
        ),
        migrations.AddIndex(
            model_name='passage',
            index=models.Index(fields=['order_within_header'], name='passages_order_w_2b4dfb_idx'),
        ),
        migrations.AddIndex(
            model_name='writingsection',
            index=models.Index(fields=['header'], name='writing_sec_header__89748d_idx'),
        ),
        migrations.AddIndex(
            model_name='writingsection',
            index=models.Index(fields=['order_within_header'], name='writing_sec_order_w_24e535_idx'),
        ),
    ]
