# Generated by Django 4.2.10 on 2025-12-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_add_headers_to_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='content_type',
            field=models.CharField(choices=[('lesson', 'Lesson'), ('section', 'Section/Passage'), ('both', 'Both')], default='both', help_text='Type of content this header is for: lessons, sections/passages, or both', max_length=20),
        ),
    ]
