# Generated by Django 4.2.10 on 2026-01-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_add_content_type_to_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_id',
            field=models.CharField(blank=True, help_text='Google OAuth ID', max_length=255, null=True, unique=True),
        ),
    ]
