# Generated by Django 4.2.10 on 2026-01-03 03:22

from django.db import migrations, models
import json


def convert_prompts_to_json(apps, schema_editor):
    """Convert existing text prompts to JSON format"""
    MathQuestion = apps.get_model('api', 'MathQuestion')
    
    for question in MathQuestion.objects.all():
        # If prompt is a string (old format), convert to JSON array
        if isinstance(question.prompt, str):
            if question.prompt.strip():
                # Convert text to a paragraph block
                question.prompt = [{"type": "paragraph", "text": question.prompt}]
            else:
                question.prompt = []
            question.save()


def reverse_convert_prompts_to_text(apps, schema_editor):
    """Convert JSON prompts back to text (for rollback)"""
    MathQuestion = apps.get_model('api', 'MathQuestion')
    
    for question in MathQuestion.objects.all():
        # If prompt is a list (JSON format), convert to text
        if isinstance(question.prompt, list):
            # Extract text from all paragraph blocks
            text_parts = []
            for block in question.prompt:
                if isinstance(block, dict):
                    if block.get('type') == 'paragraph' and block.get('text'):
                        text_parts.append(block['text'])
                    elif block.get('type') == 'side_by_side':
                        # Extract explanation text from side-by-side blocks
                        rows = block.get('rows', [])
                        if not rows and block.get('explanation'):
                            rows = [{'explanation': block.get('explanation', '')}]
                        for row in rows:
                            if row.get('explanation'):
                                text_parts.append(row['explanation'])
            question.prompt = ' '.join(text_parts)
            question.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_user_google_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mathquestion',
            name='prompt',
            field=models.JSONField(default=list, help_text='Array of prompt blocks (paragraph, side_by_side, etc.)'),
        ),
        migrations.RunPython(convert_prompts_to_json, reverse_convert_prompts_to_text),
    ]
