# Generated by Django 4.2.10 on 2026-01-03 03:36

from django.db import migrations, models
import json


def convert_lesson_question_data_to_json(apps, schema_editor):
    """Convert existing text prompts and explanations to JSON format"""
    from django.db import connection
    with connection.cursor() as cursor:
        # Convert text field
        cursor.execute("SELECT id, text FROM lesson_questions WHERE text IS NOT NULL")
        rows = cursor.fetchall()
        
        for question_id, text_value in rows:
            if text_value and isinstance(text_value, str):
                # Convert text to JSON array
                if text_value.strip():
                    text_json = json.dumps([{"type": "paragraph", "text": text_value}])
                else:
                    text_json = json.dumps([])
                
                cursor.execute(
                    "UPDATE lesson_questions SET text_json = %s::jsonb WHERE id = %s",
                    [text_json, question_id]
                )
        
        # Convert explanation field
        cursor.execute("SELECT id, explanation FROM lesson_questions WHERE explanation IS NOT NULL AND explanation != ''")
        rows = cursor.fetchall()
        
        for question_id, explanation_value in rows:
            if explanation_value and isinstance(explanation_value, str):
                # Convert text to JSON array
                if explanation_value.strip():
                    explanation_json = json.dumps([{"type": "paragraph", "text": explanation_value}])
                else:
                    explanation_json = json.dumps([])
                
                cursor.execute(
                    "UPDATE lesson_questions SET explanation_json = %s::jsonb WHERE id = %s",
                    [explanation_json, question_id]
                )


def reverse_convert_lesson_question_data_to_text(apps, schema_editor):
    """Convert JSON prompts and explanations back to text (for rollback)"""
    from django.db import connection
    with connection.cursor() as cursor:
        # Convert text_json back to text
        cursor.execute("SELECT id, text_json FROM lesson_questions WHERE text_json IS NOT NULL")
        rows = cursor.fetchall()
        
        for question_id, text_json in rows:
            if text_json:
                try:
                    if isinstance(text_json, str):
                        text_data = json.loads(text_json)
                    else:
                        text_data = text_json
                    
                    if isinstance(text_data, list):
                        text_parts = []
                        for block in text_data:
                            if isinstance(block, dict):
                                if block.get('type') == 'paragraph' and block.get('text'):
                                    text_parts.append(block['text'])
                                elif block.get('type') == 'side_by_side':
                                    rows = block.get('rows', [])
                                    if not rows and block.get('explanation'):
                                        rows = [{'explanation': block.get('explanation', '')}]
                                    for row in rows:
                                        if row.get('explanation'):
                                            text_parts.append(row['explanation'])
                        text_value = ' '.join(text_parts)
                    else:
                        text_value = str(text_data)
                    
                    cursor.execute(
                        "UPDATE lesson_questions SET text = %s WHERE id = %s",
                        [text_value, question_id]
                    )
                except (json.JSONDecodeError, TypeError):
                    pass
        
        # Convert explanation_json back to explanation
        cursor.execute("SELECT id, explanation_json FROM lesson_questions WHERE explanation_json IS NOT NULL")
        rows = cursor.fetchall()
        
        for question_id, explanation_json in rows:
            if explanation_json:
                try:
                    if isinstance(explanation_json, str):
                        explanation_data = json.loads(explanation_json)
                    else:
                        explanation_data = explanation_json
                    
                    if isinstance(explanation_data, list):
                        text_parts = []
                        for block in explanation_data:
                            if isinstance(block, dict):
                                if block.get('type') == 'paragraph' and block.get('text'):
                                    text_parts.append(block['text'])
                                elif block.get('type') == 'side_by_side':
                                    rows = block.get('rows', [])
                                    if not rows and block.get('explanation'):
                                        rows = [{'explanation': block.get('explanation', '')}]
                                    for row in rows:
                                        if row.get('explanation'):
                                            text_parts.append(row['explanation'])
                        explanation_value = ' '.join(text_parts)
                    else:
                        explanation_value = str(explanation_data)
                    
                    cursor.execute(
                        "UPDATE lesson_questions SET explanation = %s WHERE id = %s",
                        [explanation_value, question_id]
                    )
                except (json.JSONDecodeError, TypeError):
                    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_change_math_question_prompt_to_json'),
    ]

    operations = [
        # Step 1: Add temporary JSONFields
        migrations.AddField(
            model_name='lessonquestion',
            name='text_json',
            field=models.JSONField(default=list, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='lessonquestion',
            name='explanation_json',
            field=models.JSONField(default=list, null=True, blank=True),
        ),
        # Step 2: Convert data from text to JSON in temporary fields
        migrations.RunPython(convert_lesson_question_data_to_json, reverse_convert_lesson_question_data_to_text),
        # Step 3: Remove old text fields
        migrations.RemoveField(
            model_name='lessonquestion',
            name='text',
        ),
        migrations.RemoveField(
            model_name='lessonquestion',
            name='explanation',
        ),
        # Step 4: Rename temporary fields to original names
        migrations.RenameField(
            model_name='lessonquestion',
            old_name='text_json',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='lessonquestion',
            old_name='explanation_json',
            new_name='explanation',
        ),
        # Step 5: Update fields to finalize them
        migrations.AlterField(
            model_name='lessonquestion',
            name='text',
            field=models.JSONField(default=list, help_text='Array of prompt blocks (paragraph, side_by_side, etc.)'),
        ),
        migrations.AlterField(
            model_name='lessonquestion',
            name='explanation',
            field=models.JSONField(blank=True, default=list, help_text='Array of explanation blocks', null=True),
        ),
    ]
