# Generated by Django 4.2.10 on 2026-01-03 03:36

from django.db import migrations, models
import json


def convert_lesson_question_data_to_json(apps, schema_editor):
    """Convert existing text prompts and explanations to JSON format"""
    LessonQuestion = apps.get_model('api', 'LessonQuestion')
    
    # Use ORM for database-agnostic approach
    questions = LessonQuestion.objects.all()
    
    for question in questions:
        # Convert text field
        if question.text and isinstance(question.text, str):
            # Convert text to JSON array
            if question.text.strip():
                question.text_json = [{"type": "paragraph", "text": question.text}]
            else:
                question.text_json = []
            question.save(update_fields=['text_json'])
        
        # Convert explanation field
        if question.explanation and isinstance(question.explanation, str):
            # Convert text to JSON array
            if question.explanation.strip():
                question.explanation_json = [{"type": "paragraph", "text": question.explanation}]
            else:
                question.explanation_json = []
            question.save(update_fields=['explanation_json'])


def reverse_convert_lesson_question_data_to_text(apps, schema_editor):
    """Convert JSON prompts and explanations back to text (for rollback)"""
    LessonQuestion = apps.get_model('api', 'LessonQuestion')
    
    # Use ORM for database-agnostic approach
    questions = LessonQuestion.objects.all()
    
    for question in questions:
        # Convert text_json back to text
        if question.text_json:
            try:
                text_data = question.text_json
                
                if isinstance(text_data, list):
                    text_parts = []
                    for block in text_data:
                        if isinstance(block, dict):
                            if block.get('type') == 'paragraph' and block.get('text'):
                                text_parts.append(block['text'])
                            elif block.get('type') == 'side_by_side':
                                rows = block.get('rows', [])
                                if not rows and block.get('explanation'):
                                    rows = [{'explanation': block.get('explanation', '')}]
                                for row in rows:
                                    if row.get('explanation'):
                                        text_parts.append(row['explanation'])
                    text_value = ' '.join(text_parts)
                else:
                    text_value = str(text_data)
                
                question.text = text_value
                question.save(update_fields=['text'])
            except (json.JSONDecodeError, TypeError):
                pass
        
        # Convert explanation_json back to explanation
        if question.explanation_json:
            try:
                explanation_data = question.explanation_json
                
                if isinstance(explanation_data, list):
                    text_parts = []
                    for block in explanation_data:
                        if isinstance(block, dict):
                            if block.get('type') == 'paragraph' and block.get('text'):
                                text_parts.append(block['text'])
                            elif block.get('type') == 'side_by_side':
                                rows = block.get('rows', [])
                                if not rows and block.get('explanation'):
                                    rows = [{'explanation': block.get('explanation', '')}]
                                for row in rows:
                                    if row.get('explanation'):
                                        text_parts.append(row['explanation'])
                    explanation_value = ' '.join(text_parts)
                else:
                    explanation_value = str(explanation_data)
                
                question.explanation = explanation_value
                question.save(update_fields=['explanation'])
            except (json.JSONDecodeError, TypeError):
                pass


class Migration(migrations.Migration):
    atomic = False  # Make the entire migration non-atomic to avoid trigger issues

    dependencies = [
        ('api', '0024_change_math_question_prompt_to_json'),
    ]

    operations = [
        # Step 1: Add temporary JSONFields
        migrations.AddField(
            model_name='lessonquestion',
            name='text_json',
            field=models.JSONField(default=list, null=True, blank=True),
        ),
        migrations.AddField(
            model_name='lessonquestion',
            name='explanation_json',
            field=models.JSONField(default=list, null=True, blank=True),
        ),
        # Step 2: Convert data from text to JSON in temporary fields (non-atomic)
        migrations.RunPython(convert_lesson_question_data_to_json, reverse_convert_lesson_question_data_to_text, atomic=False),
        # Step 3: Make old fields nullable first (to avoid constraint issues)
        migrations.AlterField(
            model_name='lessonquestion',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lessonquestion',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        # Step 4: Remove old text fields
        migrations.RemoveField(
            model_name='lessonquestion',
            name='text',
        ),
        migrations.RemoveField(
            model_name='lessonquestion',
            name='explanation',
        ),
        # Step 5: Rename temporary fields to original names
        migrations.RenameField(
            model_name='lessonquestion',
            old_name='text_json',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='lessonquestion',
            old_name='explanation_json',
            new_name='explanation',
        ),
        # Step 6: Update fields to finalize them
        migrations.AlterField(
            model_name='lessonquestion',
            name='text',
            field=models.JSONField(default=list, help_text='Array of prompt blocks (paragraph, side_by_side, etc.)'),
        ),
        migrations.AlterField(
            model_name='lessonquestion',
            name='explanation',
            field=models.JSONField(blank=True, default=list, help_text='Array of explanation blocks', null=True),
        ),
    ]
