# Generated by Django 4.2.10 on 2026-01-16 03:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_change_lesson_question_text_to_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionClassification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="Classification name (e.g., 'Subject-Verb Agreement')", max_length=255, unique=True)),
                ('category', models.CharField(choices=[('reading', 'Reading'), ('writing', 'Writing'), ('math', 'Math')], help_text='Which section this classification belongs to', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Optional description of what this classification covers')),
                ('display_order', models.IntegerField(default=0, help_text='Order for display (higher numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'question_classifications',
                'ordering': ['category', '-display_order', 'name'],
                'indexes': [models.Index(fields=['category'], name='question_cl_categor_8cce79_idx'), models.Index(fields=['display_order'], name='question_cl_display_e16d19_idx')],
            },
        ),
        migrations.AddField(
            model_name='lessonquestion',
            name='classifications',
            field=models.ManyToManyField(blank=True, help_text='Classifications/tags for this question (for tracking user strengths/weaknesses)', related_name='lesson_questions', to='api.questionclassification'),
        ),
        migrations.AddField(
            model_name='question',
            name='classifications',
            field=models.ManyToManyField(blank=True, help_text='Classifications/tags for this question (for tracking user strengths/weaknesses)', related_name='passage_questions', to='api.questionclassification'),
        ),
    ]
