# Generated by Django 4.2.10 on 2026-01-17 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_question_classifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='is_diagnostic',
            field=models.BooleanField(default=False, help_text='If true, this lesson is the diagnostic test for its lesson_type (only one per type)'),
        ),
        migrations.CreateModel(
            name='StudyPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reading_performance', models.JSONField(blank=True, default=dict, help_text='Reading classification performance')),
                ('writing_performance', models.JSONField(blank=True, default=dict, help_text='Writing classification performance')),
                ('math_performance', models.JSONField(blank=True, default=dict, help_text='Math classification performance')),
                ('reading_diagnostic_completed', models.BooleanField(default=False)),
                ('writing_diagnostic_completed', models.BooleanField(default=False)),
                ('math_diagnostic_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('math_diagnostic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='math_study_plans', to='api.lesson')),
                ('reading_diagnostic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reading_study_plans', to='api.lesson')),
                ('recommended_lessons', models.ManyToManyField(blank=True, related_name='recommended_for_users', to='api.lesson')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='study_plan', to=settings.AUTH_USER_MODEL)),
                ('writing_diagnostic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='writing_study_plans', to='api.lesson')),
            ],
            options={
                'db_table': 'study_plans',
            },
        ),
    ]
