# Generated by Django 4.2.10 on 2026-01-17 22:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_lesson_is_diagnostic_studyplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('correct_count', models.IntegerField()),
                ('total_questions', models.IntegerField()),
                ('time_spent_seconds', models.IntegerField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('answers_data', models.JSONField(default=list)),
                ('is_diagnostic_attempt', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='api.lesson')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lesson_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'lesson_attempts',
                'ordering': ['-completed_at'],
                'indexes': [models.Index(fields=['user', 'lesson'], name='lesson_atte_user_id_a1551d_idx'), models.Index(fields=['user'], name='lesson_atte_user_id_2b27c2_idx'), models.Index(fields=['lesson'], name='lesson_atte_lesson__1a0ea7_idx'), models.Index(fields=['completed_at'], name='lesson_atte_complet_08a251_idx'), models.Index(fields=['is_diagnostic_attempt'], name='lesson_atte_is_diag_0dd972_idx')],
            },
        ),
    ]
