# Generated by Django 4.2.10 on 2026-01-18 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_lessonattempt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studyplan',
            name='reading_diagnostic',
        ),
        migrations.AddField(
            model_name='passage',
            name='is_diagnostic',
            field=models.BooleanField(default=False, help_text='If true, this passage is the diagnostic test for reading'),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='reading_diagnostic_passage',
            field=models.ForeignKey(blank=True, help_text='Reading diagnostic is a passage', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reading_study_plans', to='api.passage'),
        ),
    ]
