# Generated by Django 4.2.10 on 2026-01-21 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_reading_diagnostic_passage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppStoreSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_transaction_id', models.CharField(help_text="Apple's original transaction ID", max_length=255, unique=True)),
                ('product_id', models.CharField(help_text="Apple product ID (e.g., 'com.keuvi.premium.monthly')", max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('in_billing_retry', 'In Billing Retry'), ('in_grace_period', 'In Grace Period'), ('revoked', 'Revoked')], default='active', max_length=20)),
                ('purchase_date', models.DateTimeField(help_text='Original purchase date')),
                ('expires_date', models.DateTimeField(help_text='Current expiration date')),
                ('is_in_intro_offer', models.BooleanField(default=False)),
                ('is_upgraded', models.BooleanField(default=False)),
                ('environment', models.CharField(default='Production', help_text='Sandbox or Production', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appstore_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'appstore_subscriptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='appstore_su_user_id_f200d5_idx'), models.Index(fields=['original_transaction_id'], name='appstore_su_origina_827245_idx'), models.Index(fields=['expires_date'], name='appstore_su_expires_f8f56f_idx')],
            },
        ),
    ]
