# Generated by Django 4.2.10 on 2026-01-23 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_add_appstore_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='apple_id',
            field=models.CharField(blank=True, help_text='Apple Sign In ID (sub claim from identity token)', max_length=255, null=True, unique=True),
        ),
    ]
