# Generated by Django 4.2.10 on 2026-02-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_add_apple_id_to_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='studyplan',
            name='diagnostic_prompt_dismissed_at',
            field=models.DateTimeField(blank=True, help_text='When user dismissed the diagnostic nudge prompt', null=True),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='first_practice_completed_at',
            field=models.DateTimeField(blank=True, help_text='When user completed their first practice session', null=True),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='onboarding_completed',
            field=models.BooleanField(default=False, help_text='Whether user has completed onboarding'),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='onboarding_state',
            field=models.CharField(choices=[('WELCOME', 'Welcome'), ('PROFILE_SETUP', 'Profile Setup'), ('DIAGNOSTIC_NUDGE', 'Diagnostic Nudge'), ('DIAGNOSTIC_IN_PROGRESS', 'Diagnostic In Progress'), ('POST_DIAGNOSTIC', 'Post Diagnostic'), ('ENGAGED', 'Engaged')], default='WELCOME', help_text='Current onboarding state', max_length=30),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='post_diagnostic_seen_at',
            field=models.DateTimeField(blank=True, help_text='When user saw the post-diagnostic prompt', null=True),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='profile_prompt_dismissed_at',
            field=models.DateTimeField(blank=True, help_text='When user dismissed the profile setup prompt', null=True),
        ),
        migrations.AddField(
            model_name='studyplan',
            name='welcome_seen_at',
            field=models.DateTimeField(blank=True, help_text='When user saw the welcome prompt', null=True),
        ),
    ]
