# Generated by Django 4.2.10 on 2026-02-10 01:01

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_add_onboarding_fields_to_studyplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(help_text="Customer-facing code (e.g., 'STUDENT20', 'WELCOME')", max_length=50, unique=True)),
                ('name', models.CharField(help_text='Display name for admin reference', max_length=255)),
                ('discount_type', models.CharField(choices=[('percent', 'Percentage Off'), ('amount', 'Fixed Amount Off')], default='percent', max_length=10)),
                ('percent_off', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage discount (1-100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('amount_off', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed amount off in cents (USD)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('duration', models.CharField(choices=[('once', 'Once (first payment only)'), ('forever', 'Forever (all recurring payments)'), ('repeating', 'Repeating (X months)')], default='forever', max_length=10)),
                ('duration_in_months', models.PositiveIntegerField(blank=True, help_text="Number of months (only for 'repeating' duration)", null=True)),
                ('max_redemptions', models.PositiveIntegerField(blank=True, help_text='Maximum total uses (leave blank for unlimited)', null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Expiration date (leave blank for no expiration)', null=True)),
                ('first_time_transaction', models.BooleanField(default=False, help_text='Only allow for first-time customers')),
                ('is_active', models.BooleanField(default=True)),
                ('stripe_coupon_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('stripe_promotion_code_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('times_redeemed', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'discount_codes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['code'], name='discount_co_code_085c69_idx'), models.Index(fields=['is_active'], name='discount_co_is_acti_f4e7bc_idx'), models.Index(fields=['expires_at'], name='discount_co_expires_1f278c_idx')],
            },
        ),
    ]
