# Generated by Django 4.2.10 on 2026-02-10 01:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_discount_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discountcode',
            name='amount_off',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Fixed amount off in cents (USD)', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
