# Generated by Django 4.2.10 on 2026-02-12 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_fix_amount_off_cents_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='discountcode',
            name='grants_premium_directly',
            field=models.BooleanField(default=False, help_text='If True, code grants premium directly without Stripe checkout (e.g., for contests, partnerships)'),
        ),
    ]
