# Generated by Django 4.2.10 on 2026-02-13 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_add_grants_premium_directly_to_discountcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='premium_granted_directly',
            field=models.BooleanField(default=False, help_text='True if premium was granted via promo code (bypasses Stripe sync)'),
        ),
    ]
