# Generated by Django 4.2.10 on 2026-02-20 05:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_add_premium_granted_directly'),
    ]

    operations = [
        migrations.AddField(
            model_name='header',
            name='background_color',
            field=models.CharField(blank=True, help_text='Header background/accent color (hex format, e.g., #1CB0F6)', max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #1CB0F6)', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='header',
            name='icon_url',
            field=models.URLField(blank=True, help_text='URL to header/unit icon image (256x256 WebP recommended)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='lesson',
            name='icon_color',
            field=models.CharField(blank=True, help_text='Primary accent color for icon/UI (hex format, e.g., #58CC02)', max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #58CC02)', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='lesson',
            name='icon_url',
            field=models.URLField(blank=True, help_text='URL to lesson icon image (256x256 WebP recommended)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='mathsection',
            name='icon_color',
            field=models.CharField(blank=True, help_text='Primary accent color for icon/UI (hex format, e.g., #58CC02)', max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #58CC02)', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='mathsection',
            name='icon_url',
            field=models.URLField(blank=True, help_text='URL to math section icon image (256x256 WebP recommended)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='passage',
            name='icon_color',
            field=models.CharField(blank=True, help_text='Primary accent color for icon/UI (hex format, e.g., #58CC02)', max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #58CC02)', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='passage',
            name='icon_url',
            field=models.URLField(blank=True, help_text='URL to passage icon image (256x256 WebP recommended)', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='writingsection',
            name='icon_color',
            field=models.CharField(blank=True, help_text='Primary accent color for icon/UI (hex format, e.g., #58CC02)', max_length=7, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color code (e.g., #58CC02)', regex='^#[0-9A-Fa-f]{6}$')]),
        ),
        migrations.AddField(
            model_name='writingsection',
            name='icon_url',
            field=models.URLField(blank=True, help_text='URL to writing section icon image (256x256 WebP recommended)', max_length=500, null=True),
        ),
    ]
