# Generated by Django 4.2.10 on 2026-02-20 06:01

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_add_visual_enhancement_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='header',
            name='icon_url',
            field=models.URLField(blank=True, help_text='URL to header/unit icon image (256x256 WebP recommended). Must be hosted on GCS bucket.', max_length=500, null=True, validators=[api.models.validate_gcs_icon_url]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='icon_url',
            field=models.URLField(blank=True, help_text='URL to lesson icon image (256x256 WebP recommended). Must be hosted on GCS bucket.', max_length=500, null=True, validators=[api.models.validate_gcs_icon_url]),
        ),
        migrations.AlterField(
            model_name='mathsection',
            name='icon_url',
            field=models.URLField(blank=True, help_text='URL to math section icon image (256x256 WebP recommended). Must be hosted on GCS bucket.', max_length=500, null=True, validators=[api.models.validate_gcs_icon_url]),
        ),
        migrations.AlterField(
            model_name='passage',
            name='icon_url',
            field=models.URLField(blank=True, help_text='URL to passage icon image (256x256 WebP recommended). Must be hosted on GCS bucket.', max_length=500, null=True, validators=[api.models.validate_gcs_icon_url]),
        ),
        migrations.AlterField(
            model_name='writingsection',
            name='icon_url',
            field=models.URLField(blank=True, help_text='URL to writing section icon image (256x256 WebP recommended). Must be hosted on GCS bucket.', max_length=500, null=True, validators=[api.models.validate_gcs_icon_url]),
        ),
    ]
